AUTHOR="Farkas Balázs / P3L47H"
APPNAME="Panoráma kép készítő alkalmazás"
FIGURE_TITLE=APPNAME + "\n"+AUTHOR
TESTPATH="3"    # 1/2/3
INCLUDED_EXTENSIONS = ['JPG', 'bmp', 'png', 'gif']
IMAGE_ARRAY_TYPE='uint8'
SAMPLING_SIZE=10
MAXTRYING=5
MIN_MATCH_COUNT=4
DEBUG_MODE=True

