AUTHOR="Farkas Balázs / P3L47H"
APPNAME="Panoráma kép készítő alkalmazás"
FIGURE_TITLE=APPNAME + "\n"+AUTHOR
PATH="C:\\Learn\Phyton\Panorama\\source\\test\\2"
#PATH="\\Test\\1"
INCLUDED_EXTENSIONS = ['JPG', 'bmp', 'png', 'gif']
IMAGE_ARRAY_TYPE='uint8'
SAMPLING_SIZE=10
MAXTRYING=5